import { cva, type VariantProps } from "class-variance-authority";
import { Slot } from "radix-ui";
import type * as React from "react";

import { cn } from "@/ui/lib/cn";

/**
 * The button, generated by the shadcn tool and then brought in line with spec
 * 0004. Three deliberate divergences from what it ships:
 *
 * 1. **No opacity modifiers.** `hover:bg-primary/90` becomes
 *    `hover:bg-primary-hover`, a declared token. A faded token is a colour that
 *    exists nowhere in `globals.css`, so `contrast.test.ts` cannot see it
 *    (invariant 11).
 * 2. **No per component focus ring.** `globals.css` declares one
 *    `:focus-visible` outline for the whole product, so every control gets the
 *    same visible, measured ring without remembering to ask for it (AC-5).
 * 3. **A readable disabled state.** `opacity-50` over a filled button leaves
 *    text that is technically exempt from contrast and still unreadable. A
 *    disabled button drops to the muted pair instead, which is measured.
 *
 * Every size clears the 24 by 24 CSS pixel minimum in WCAG 2.2 (AC-21): the
 * smallest here is `icon-xs` at 24 square.
 */
const buttonVariants = cva(
  [
    "inline-flex shrink-0 items-center justify-center gap-2 rounded-md",
    "text-sm font-medium whitespace-nowrap transition-surface",
    "disabled:pointer-events-none disabled:cursor-not-allowed",
    "aria-invalid:border-destructive",
    "[&_svg]:pointer-events-none [&_svg]:shrink-0",
    "[&_svg:not([class*='size-'])]:size-4",
  ],
  {
    variants: {
      variant: {
        default:
          "bg-primary text-primary-foreground hover:bg-primary-hover disabled:bg-muted disabled:text-muted-foreground",
        destructive:
          "bg-destructive text-destructive-foreground hover:bg-destructive-hover disabled:bg-muted disabled:text-muted-foreground",
        outline:
          "border border-input bg-background text-foreground hover:bg-accent hover:text-accent-foreground disabled:border-border disabled:text-muted-foreground",
        secondary:
          "bg-secondary text-secondary-foreground hover:bg-secondary-hover disabled:bg-muted disabled:text-muted-foreground",
        ghost:
          "text-foreground hover:bg-accent hover:text-accent-foreground disabled:text-muted-foreground",
        link: "text-primary underline-offset-4 hover:underline disabled:text-muted-foreground disabled:no-underline",
      },
      size: {
        default: "h-9 px-4 py-2 has-[>svg]:px-3",
        sm: "h-8 gap-1.5 px-3 has-[>svg]:px-2.5",
        lg: "h-10 px-6 has-[>svg]:px-4",
        icon: "size-9",
        "icon-sm": "size-8",
        // 24 square: the WCAG 2.2 target size minimum, not a pixel under.
        "icon-xs": "size-6 [&_svg:not([class*='size-'])]:size-3.5",
      },
    },
    defaultVariants: {
      variant: "default",
      size: "default",
    },
  },
);

export type ButtonVariants = VariantProps<typeof buttonVariants>;

export type ButtonProps = React.ComponentProps<"button"> &
  ButtonVariants & {
    /** Render the child element instead, keeping the styling. Used for links. */
    readonly asChild?: boolean;
  };

export function Button({
  className,
  variant = "default",
  size = "default",
  asChild = false,
  type,
  ...props
}: ButtonProps) {
  const Component = asChild ? Slot.Root : "button";

  return (
    <Component
      data-slot="button"
      data-variant={variant}
      data-size={size}
      // A `<button>` inside a form defaults to `submit`, which is how a button
      // meant to open a dialog ends up posting the form instead.
      type={asChild ? undefined : (type ?? "button")}
      className={cn(buttonVariants({ variant, size }), className)}
      {...props}
    />
  );
}

export { buttonVariants };
